### ISSUE TITLE
can I read a ximnd file by using this SDK? 

### ISSUE THREAD

**Issue by xinghenlei** [xmindltd/xmind-sdk-js#29]
How to read an xmind file and convert it to JSON

**Comment by danielsss** [comment]
I am sorry. we don't support to load an existing `xmind file` for now.

Go to #20 for more details.

**Comment by hgrourou** [comment]
> How to read an xmind file and convert it to JSON
@xinghenlei 
you can have a try for this, i have done  convert a xmind file to JSON
https://www.npmjs.com/package/xmindparser

**Comment by q2333gh** [comment]
I guess the reason why dont support is due to some commercial concern. 
If user want to convert a .xmind to .md with pictures. (that can be done by  a programmer.if there is sdk to read .xmind file ).(And . xmind12 cant export picture with .md file .)
BUT. its vip function for .xmind pro user.
So, 
Im trying to convert it to .docx firstly , Then use some .docx file convert to .md file  lib to get the goal.
