### ISSUE TITLE
Cannot locate the topic accurately if there is an identical topic existing at the same time.

### ISSUE THREAD

**Issue by cenmen** [xmindltd/xmind-sdk-js#63]
为什么只能通过 title 去获取 component Id 呢？有重复的 title 的时候就获取不到想要获取的正确的 topic 了，例如我有两个子主题的 title 同时为 A ，然后我需要在第二个 A 下添加一个子 title ，我只能通过 topic.on(topic.cid('A')).add({title: 'child for A'}) 去添加，但是这样是添加到第一个 A 下。（存在相同主题 title 是常见场景吧）

**Comment by danielsss** [comment]
> 为什么只能通过 title 去获取 component Id 呢？有重复的 title 的时候就获取不到想要获取的正确的 topic 了，例如我有两个子主题的 title 同时为 A ，然后我需要在第二个 A 下添加一个子 title ，我只能通过 topic.on(topic.cid('A')).add({title: 'child for A'}) 去添加，但是这样是添加到第一个 A 下。（存在相同主题 title 是常见场景吧）

解决相同主题 componentId 的办法如下：

```js
// 第一次添加 Topic A
const componentId_1 = topic.cid('A');// cid 会生成一个全局唯一的 componentId

// 第二次添加 Topic A
const componentId_2 = topic.cid('A');

// componentId_1 !== componentId_2

topic.on(componentId_1).add(...)
topic.on(componentId_2).add(...) 
```

使用文档中有提示过，如果想使用 title 获取 componentId, 应避免重复的 title [详情](https://github.com/xmindltd/xmind-sdk-js#cidtitle--string)

你有好的想法或是建议可以提出，当然也非常欢迎 PR

**Comment by cenmen** [comment]
> > 为什么只能通过 title 去获取 component Id 呢？有重复的 title 的时候就获取不到想要获取的正确的 topic 了，例如我有两个子主题的 title 同时为 A ，然后我需要在第二个 A 下添加一个子 title ，我只能通过 topic.on(topic.cid('A')).add({title: 'child for A'}) 去添加，但是这样是添加到第一个 A 下。（存在相同主题 title 是常见场景吧）
> 
> 解决相同主题 componentId 的办法如下：
> 
> ```js
> // 第一次添加 Topic A
> const componentId_1 = topic.cid('A');// cid 会生成一个全局唯一的 componentId
> 
> // 第二次添加 Topic A
> const componentId_2 = topic.cid('A');
> 
> // componentId_1 !== componentId_2
> 
> topic.on(componentId_1).add(...)
> topic.on(componentId_2).add(...) 
> ```
> 
> 使用文档中有提示过，如果想使用 title 获取 componentId, 应避免重复的 title [详情](https://github.com/xmindltd/xmind-sdk-js#cidtitle--string)
> 
> 你有好的想法或是建议可以提出，当然也非常欢迎 PR

非常感谢，解决了我的问题。没有想到通过 topic.cid('A') 创建完 component ID 后存起来。

**Comment by cenmen** [comment]
> > 为什么只能通过 title 去获取 component Id 呢？有重复的 title 的时候就获取不到想要获取的正确的 topic 了，例如我有两个子主题的 title 同时为 A ，然后我需要在第二个 A 下添加一个子 title ，我只能通过 topic.on(topic.cid('A')).add({title: 'child for A'}) 去添加，但是这样是添加到第一个 A 下。（存在相同主题 title 是常见场景吧）
> 
> 解决相同主题 componentId 的办法如下：
> 
> ```js
> // 第一次添加 Topic A
> const componentId_1 = topic.cid('A');// cid 会生成一个全局唯一的 componentId
> 
> // 第二次添加 Topic A
> const componentId_2 = topic.cid('A');
> 
> // componentId_1 !== componentId_2
> 
> topic.on(componentId_1).add(...)
> topic.on(componentId_2).add(...) 
> ```
> 
> 使用文档中有提示过，如果想使用 title 获取 componentId, 应避免重复的 title [详情](https://github.com/xmindltd/xmind-sdk-js#cidtitle--string)
> 
> 你有好的想法或是建议可以提出，当然也非常欢迎 PR

你好，我的代码是这样的，连续添加两个 title 之后，后续如何在指定某个的 A 下再添加子 title
```
topic
  .on(topic.cid())
  .add({title: 'A'})
  .add({title: 'A'})
```

**Comment by danielsss** [comment]
@cenmen 只能判断如果主题相同，则存储不同的 uniqueId，然后去根据 uniqueId 操作。

```js
const root = topic.cid();
topic.on(root);
topic.add({ title: 'a' });
const a1 = topic.cid();
topic.add({ title: 'a' });
const a2 = topic.cid();

topic.on(a1).add(...);
topic.on(a2).add(...);
```

**Comment by danielsss** [comment]
### I've added 2 new features for this issue.

* The `componentId` could be obtained by `Topic.cid('topic1', /* Optional */{ parentId: '...' })` with a parentId, but it must be in a different branch. Otherwise, the first one that matched with your `parentId` and `title` would be returned.

* I think that would be very malformed if we put a couple of identical topics under the same root topic. Anyway, now you can attach a `customId` when you add a new topic.

For instance:

```js
topic.on(...).add({ title: 'topic 1', /* Optional */customId: 'Your Id' });
```

* [ usage case ](https://github.com/xmindltd/xmind-sdk-js/blob/feat/tree_model/test/units/topic.test.ts#L165)

All the features have been pushed on the [branch](https://github.com/xmindltd/xmind-sdk-js/tree/feat/tree_model), but I still need more time to make sure that everything is going on the right way.

If you have any better ideas, please leave them here. 😁
